const cuisineData=[
    { label: 'african', value: '1' },
    { label: 'asian', value: '2' },
    { label: 'american', value: '3' },
    { label: 'british', value: '4' },
    { label: 'cajun', value: '5' },
    { label: 'caribbean', value: '6' },
    { label: 'chinese', value: '7' },
    { label: 'eastern European', value: '8' },
    { label: 'european', value: '9' },
    { label: 'french', value: '10' },
    { label: 'german', value: '11' },
    { label: 'greek', value: '12' },
    { label: 'indian', value: '13' },
    { label: 'irish', value: '14' },
    { label: 'italian', value: '15' },
    { label: 'japanese', value: '16' },
    { label: 'jewish', value: '17' },
    { label: 'korean', value: '18' },
    { label: 'latin american', value: '19' },
    { label: 'mediterranean', value: '20' },
    { label: 'mexican', value: '21' },
    { label: 'middle eastern', value: '22' },
    { label: 'nordic', value: '23' },
    { label: 'southern', value: '24' },
    { label: 'spanish', value: '25' },
    { label: 'thai', value: '26' },
    { label: 'vietnamese', value: '27' },
  ]

export default cuisineData; 