const cuisineData=[
    { label: 'African', value: '1' },
    { label: 'Asian', value: '2' },
    { label: 'American', value: '3' },
    { label: 'British', value: '4' },
    { label: 'Cajun', value: '5' },
    { label: 'Caribbean', value: '6' },
    { label: 'Chinese', value: '7' },
    { label: 'Eastern European', value: '8' },
    { label: 'European', value: '9' },
    { label: 'French', value: '10' },
    { label: 'German', value: '11' },
    { label: 'Greek', value: '12' },
    { label: 'Indian', value: '13' },
    { label: 'Irish', value: '14' },
    { label: 'Italian', value: '15' },
    { label: 'Japanese', value: '16' },
    { label: 'Jewish', value: '17' },
    { label: 'Korean', value: '18' },
    { label: 'Latin American', value: '19' },
    { label: 'Mediterranean', value: '20' },
    { label: 'Mexican', value: '21' },
    { label: 'Middle Eastern', value: '22' },
    { label: 'Nordic', value: '23' },
    { label: 'Southern', value: '24' },
    { label: 'Spanish', value: '25' },
    { label: 'Thai', value: '26' },
    { label: 'Vietnamese', value: '27' },
  ]

export default cuisineData; 